ledger_account.ledger_account_type.*:
  type: config_entity
  label: 'Ledger Account type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Fundamental type'
    uuid:
      type: string
